cookie:
  expiry_days: 30
  key: shipathon_project_cookie_key
  name: shipathon_project_cookie_name
credentials:
  usernames:
    hello:
      email: hello@hello.hello
      failed_login_attempts: 0
      first_name: Hello
      last_name: world
      logged_in: false
      password: $2b$12$/wAEC16BLZZORWXUOh1ul.efp.vdjPHy5UfKdACU8s6SmMbf/V91e
      password_hint: HelloWorld@1
      roles:
      - viewer
    reddragonnm:
      email: neeleshojmishra@gmail.com
      failed_login_attempts: 0
      first_name: Neelesh
      last_name: Mishra
      logged_in: true
      password: $2b$12$GgYVfWkMCLOto0NH7rlXxeVA9GI/Gnh/.UzJ5yn6P6FdJOWNt5fUm
      roles:
      - admin
      - editor
      - viewer
